services:
  app:
    # Henter backend-imaget fra GitHub Container Registry
    image: ghcr.io/codebynajib/billigtshirt-webshop-backend:latest
    restart: on-failure # <--- Dette sikrer, at den prøver igen indtil databasen svarer
    ports:
      - "8080:8080"


    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/billigtshirtdb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

      # 2. Fortæl Flyway at den skal lede inde i JAR-filen (classpath)
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration

      # 3. Aktiver Flyway og bed Hibernate om at slappe af
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

      # 4. Tænd for DEBUG logs, så vi kan se, hvad Flyway laver
      - LOGGING_LEVEL_ORG_FLYWAYDB=DEBUG

    depends_on:
      db:
        condition: service_healthy

  frontend:
    # Frontend-image er ændret til standard
     image: nginx:alpine
     container_name: frontend
     ports:
       - "8081:80" # Vi ændrer her, så fremadrettet tilgår vi shoppen på port 8081
     volumes:
       - ./frontend-t-shirt:/usr/share/nginx/html:ro
       - ./frontend-t-shirt/default.conf:/etc/nginx/conf.d/default.conf:ro  # <--- VIGTIG: Denne linje aktiverer vores konfiguration
     depends_on:
       - app
  db:
    # Specifik MySQL version (god praksis for stabilitet)
    image: mysql:8.0@sha256:0275a35e79c60caae68fac520602d9f6897feb9b0941a1471196b1a01760e581
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: billigtshirtdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
