name: CI - Compile & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Tjek koden ud
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      # 2. Opsæt JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Cache Maven dependencies
          # path = hvad vi gemmer
          #key = hvilken version af cachen der passer til vores pom.xml
          #restore-keys = backup-cache hvis key ikke matcher

      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # 4. Gør mvnw executable
      - name: Make mvnw executable
        run: chmod +x backend-t-shirt/mvnw

      # 5. Compile koden
      - name: Compile code
        run: mvnw clean compile
        working-directory: backend-t-shirt

      # 6. Kør tests
      - name: Run tests
        run: mvnw test
        working-directory: backend-t-shirt
