name: CI-Pipeline - Billig T-Shirt

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: backend-t-shirt

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # pinned SHA (release v6.0.1, 2025-12-02)

      - name: Set up JDK 21
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # pinned SHA (release v5.0.1, 2025-11-01)
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # pinned SHA (release v5.0.1, 2025-12-09)
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('backend-t-shirt/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run tests
        run: mvn -B -ntp test
